### ISSUE TITLE
Bad version number

### ISSUE THREAD

**Issue by Neospiro** [FichteFoll/InsertDate#27]
Sublime Package Control update my InsertDate plugin all the day.
I see this is a version number problem ( 1.0.1 in the package metadata and 2.0.1 in the Package Control website)

Thank you

**Comment by FichteFoll** [comment]
> update my InsertDate plugin all the day

Do you mean the update message gets displayed every restart? If so, I can use this to pass manual update instructions.

The reason for this issue is covered in #25 and is a bad interaction between InsertDate and Package Control (but mostly PC). You need to remove the package manually and then reinstall or update it in order to trigger a real update, until Package Control gets updated.
