### ISSUE TITLE
Don't require selecting a timezone

### ISSUE THREAD

**Issue by vith** [FichteFoll/InsertDate#30]
For example:

```shell-session
❯ echo 'import time; print(time.strftime("%c %Z"))' | python
Sat Dec 12 18:41:27 2015 CST
```

When traveling across timezones, I should only have to change the timezone configuration in one place: my OS.

**Comment by FichteFoll** [comment]
You can just ... not select a timezone, actually. It will default to the system locale. `%Z` is most likely not supported however, because I had terribly annoying unicode issues with it when I initially wrote the tool (so mostly Python 2-related - I hope).

I suppose I could try to fix it for you, because nobody else has requested `%Z` for the `locale` timezone so far.

**Comment by vith** [comment]
Oh, I didn't get the feeling it was optional when it popped up I guess.

And the format in my example isn't really important, I was just checking/demonstrating that python doesn't need me to tell it what timezone to use.

**Comment by FichteFoll** [comment]
The reason why I'm prompting users to insert a timezone is actually just because `%Z` doesn't work on the default `locale` timezone input classifier. [The popup](https://github.com/FichteFoll/InsertDate/blob/186cc1a8a069a6bbdf40e39b5d81cff9f402e7a6/insert_date.py#L378-L384) that appears on installation is quite open about that, imo, and does not force you to reply. I mean, it's an ok-cancel dialog.

**Comment by FichteFoll** [comment]
I created #31 to represent the actual underlying issue and close this as a "question" kinda issue.
